version: 2

updates:
  - package-ecosystem: "nuget"
    directories:
      - "/src/*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "FSharp.Core"
        update-types: [ "version-update:semver-minor", "version-update:semver-patch" ]
    groups:
      deps:
        patterns: [ "*" ]
  - package-ecosystem: "nuget"
    directories:
      - "/tests/*"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "FSharp.Core"
        update-types: [ "version-update:semver-minor", "version-update:semver-patch" ]
    groups:
      tests:
        patterns: [ "*" ]